# -*- coding: utf-8 -*-
"""conditional statement QA solving

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vj-m5vRiGv5GsH5XhC4z2Fs5A74-m-95
"""

#Conditional Statement problem solving questions -

#🔹 Part 1: Technical Questions (10)

#- Write a program to check whether a given number is positive, negative, or zero.

num1 = 1

if(num1 > 0):
  print("Positive")
elif(num1 == 0):
    print("Zero")
else:
    print("negative")

#- Write a program that checks if a given number is even or odd.

num1=11

if(num1 % 2 == 0):
  print("Even")
else:
  print("Odd")

#- Write a program to check whether a given year is a leap year or not.

year = 1900


if year % 400 == 0:
    print("Leap Year")
elif year % 100 == 0:
    print("Not a Leap Year")
elif year % 4 == 0:
    print("Leap Year")
else:
    print("Not a Leap Year")

#- Write a program to find the greatest of two numbers entered by the user.

num1 = 1
num2 = 2

if (num1 > num2):
  print(num1)
elif (num2 > num1):
  print (num2)
else:
  print("Both are equal")

#- Write a program to find the greatest among three numbers entered by the user.

num1 = 1
num2 = 2
num3 = 3

if (num1 > num2 and num1 > num3):
  print(num1)
elif (num2 > num1 and num2 > num3):
  print (num2)
else:
  print(num3)

#- Write a program that checks whether a given number is divisible by 5 or not.

num =9

if(num % 5 == 0):
  print("divisible by 5")
else:
  print("Not divisible by 5")

#- Write a program to check whether a given character is a vowel or a consonant.

vowel= "A"

if(vowel == "A" or vowel == "a"):
  print("It is a vowel")
elif(vowel== "E" or vowel == "e"):
    print("It is a vowel")
elif(vowel== "I" or vowel == "i"):
    print("It is a vowel")
elif(vowel== "O" or vowel == "o"):
    print("It is a vowel")
elif(vowel== "U" or vowel == "u"):
    print("It is a vowel")
else:
  print("It is a consonant")

#- Write a program to check whether a student has passed or failed an exam. (Passing marks = 40).

marks = 30

if (marks >= 40):
  print("Pass")
else:
  print("Fail")

#- Write a program that checks whether a given number is within the range 10 to 50 or not.

num = 49

if num >= 10 and num <=50:
  print("It is within the range")
else:
  print('Not lies within the range')

#Write a program to check if a number is multiple of 3, multiple of 7, or neither.

num = 8

if num % 3 == 0 and num % 7 == 0:
    print("It is a multiple of both 3 and 7")
elif num % 3 == 0:
    print("It is a multiple of 3")
elif num % 7 == 0:
    print("It is a multiple of 7")
else:
    print("It is not a multiple of 3 or 7")

"""🔹 Part 2: Real-life Based Questions (10)"""

#- A shopkeeper gives a 10% discount if the purchase amount is more than 500. Otherwise, no discount. Write a program to check discount eligibility.

prod_amt = 600

if(prod_amt > 500):
  print(prod_amt*0.90)
else:
  print(prod_amt)

#- A person can vote if his/her age is 18 or above. Otherwise, not eligible. Write a program.

age= 19

if(age>=18):
  print("Eligible for voting")
else:
  print("Not eligible")

#A traffic light shows Red → Stop, Yellow → Wait, Green → Go. Write a program to print the action based on the light color.

colour = "Black"

if colour == "Red":
  print("Stop")
elif colour == "Yellow":
  print("Wait")
elif colour == "Green":
  print("Go")
else:
  print("Invalid colour")

# - A student’s grade is decided as:

#     Marks ≥ 90 → Grade A

#     Marks ≥ 75 → Grade B

#     Marks ≥ 50 → Grade C

#     Otherwise → Fail


marks = 86

if marks >= 90:
  print("Grade A")
elif marks >= 75:
  print("Grade B")
elif marks >= 50:
  print("Grade C")
else:
  print("Fail")

#- Write a program to check whether a person is child (0–12), teen (13–19), adult (20–59), or senior citizen (60+).

Age= 60

if Age >=0 and Age <=12:
  print("child")
elif Age >=13 and Age <=19:
  print("teen")
elif Age >=20 and Age <=59:
  print("Adult")
else:
  print("senior citizen")

# - A cinema ticket costs 200. If the person’s age is below 12, ticket costs 100. If age is above 60, ticket costs 150. Otherwise, normal price. Write a program.

age = 2

if age < 12:
  print("Ticket prize","=",100)
elif age > 60:
  print("Ticket prize","=",150)
else:
  print("Ticket prize","=",200)

# - A company gives a bonus to employees: If experience ≥ 5 years, bonus = 10,000 else bonus = 5,000. Write a program to calculate bonus.

exp = 2

if exp >= 5:
  print("Bonus","=",10000)
else:
  print("Bonus","=",5000)

# - A weather app shows:

#     Temp < 0 → "Freezing Weather"

#     Temp 0–20 → "Cold Weather"

#     Temp 21–35 → "Normal Weather"

#     Temp > 35 → "Hot Weather"

#     Write a program.


temp1 = 31

if temp1 < 0:
  print("Freezing Weather")
elif temp1 <=20:
  print("Cold Weather")
elif temp1 <=35:
  print("Normal Weather")
else:
  print('Hot Weather')

# - An ATM allows withdrawal only if amount ≤ balance. Otherwise, print “Insufficient Balance”. Write a program.

amt = 10000
balance = 20000

if amt <= balance:
  print("withdrawal","=",amt)
else:
  print("Insufficient balance")

# - A student gets scholarship if marks ≥ 85. Otherwise, no scholarship. Write a program.

marks = 60

if marks >= 85:
  print("Student will get scholarship")
else:
  print("No scholarship")

#Write a program to check if a number is multiple of 3,multiple of 5, multiple of 7, or neither

num = 8

if num % 3 == 0 and num % 5 == 0 and num % 7 == 0:
    print("It is divisible by 3, 5 and 7")
elif num % 3 == 0 and num % 5 == 0:
    print("It is divisible by 3 and 5")
elif num % 3 == 0 and num % 7 == 0:
    print("It is divisible by 3 and 7")
elif num % 5 == 0 and num % 7 == 0:
    print("It is divisible by 5 and 7")
elif num % 3 == 0:
    print("It is divisible by 3")
elif num % 5 == 0:
    print("It is divisible by 5")
elif num % 7 == 0:
    print("It is divisible by 7")
else:
    print("It is not divisible by 3, 5 and 7")

# Write a Python program to print the ascending and descending order
# of four numbers which are strictly differ from each other

num1 = int(input("Enter any number here 1: "))
num2 = int(input("Enter any number here 2: "))
num3 = int(input("Enter any number here 3: "))
num4 = int(input("Enter any number here 4: "))

if num1 == num2 == num3 == num4:
    print("All values are equal, please provide different values.")
elif num1 == num2 and num1 == num3:
    print("num1, num2 and num3 are equal, please provide different values.")
elif num1 == num2 and num1 == num4:
    print("num1, num2 and num4 are equal, please provide different values.")
elif num1 == num3 and num1 == num4:
    print("num1, num3 and num4 are equal, please provide different values.")
elif num2 == num3 and num2 == num4:
    print("num2, num3 and num4 are equal, please provide different values.")
elif num1 == num2:
    print("num1 and num2 are equal, please provide different values.")
elif num1 == num3:
    print("num1 and num3 are equal, please provide different values.")
elif num1 == num4:
    print("num1 and num4 are equal, please provide different values.")
elif num2 == num3:
    print("num2 and num3 are equal, please provide different values.")
elif num2 == num4:
    print("num2 and num4 are equal, please provide different values.")
elif num3 == num4:
    print("num3 and num4 are equal, please provide different values.")
else:

    if num1 < num2 and num1 < num3 and num1 < num4:
        if num2 < num3 and num2 < num4 and num3 < num4:
            print(num1, num2, num3, num4)
        elif num2 < num3 and num2 < num4 and num4 < num3:
            print(num1, num2, num4, num3)
        elif num3 < num2 and num3 < num4 and num2 < num4:
            print(num1, num3, num2, num4)
        elif num3 < num2 and num3 < num4 and num4 < num2:
            print(num1, num3, num4, num2)
        elif num4 < num2 and num4 < num3 and num2 < num3:
            print(num1, num4, num2, num3)
        else:
            print(num1, num4, num3, num2)

    elif num2 < num1 and num2 < num3 and num2 < num4:
        if num1 < num3 and num1 < num4 and num3 < num4:
            print(num2, num1, num3, num4)
        elif num1 < num3 and num1 < num4 and num4 < num3:
            print(num2, num1, num4, num3)
        elif num3 < num1 and num3 < num4 and num1 < num4:
            print(num2, num3, num1, num4)
        elif num3 < num1 and num3 < num4 and num4 < num1:
            print(num2, num3, num4, num1)
        elif num4 < num1 and num4 < num3 and num1 < num3:
            print(num2, num4, num1, num3)
        else:
            print(num2, num4, num3, num1)

    elif num3 < num1 and num3 < num2 and num3 < num4:
        if num1 < num2 and num1 < num4 and num2 < num4:
            print(num3, num1, num2, num4)
        elif num1 < num2 and num1 < num4 and num4 < num2:
            print(num3, num1, num4, num2)
        elif num2 < num1 and num2 < num4 and num1 < num4:
            print(num3, num2, num1, num4)
        elif num2 < num1 and num2 < num4 and num4 < num1:
            print(num3, num2, num4, num1)
        elif num4 < num1 and num4 < num2 and num1 < num2:
            print(num3, num4, num1, num2)
        else:
            print(num3, num4, num2, num1)

    elif num4 < num1 and num4 < num2 and num4 < num3:
        if num1 < num2 and num1 < num3 and num2 < num3:
            print(num4, num1, num2, num3)
        elif num1 < num2 and num1 < num3 and num3 < num2:
            print(num4, num1, num3, num2)
        elif num2 < num1 and num2 < num3 and num1 < num3:
            print(num4, num2, num1, num3)
        elif num2 < num1 and num2 < num3 and num3 < num1:
            print(num4, num2, num3, num1)
        elif num3 < num1 and num3 < num2 and num1 < num2:
            print(num4, num3, num1, num2)
        else:
            print(num4, num3, num2, num1)

# Write a Python program to print the descending order
# of four numbers which are strictly differ from each other

num1 = int(input("Enter any number here 1: "))
num2 = int(input("Enter any number here 2: "))
num3 = int(input("Enter any number here 3: "))
num4 = int(input("Enter any number here 4: "))

if num1 == num2 == num3 == num4:
    print("All values are equal, please provide different values.")
elif num1 == num2 and num1 == num3:
    print("num1, num2 and num3 are equal, please provide different values.")
elif num1 == num2 and num1 == num4:
    print("num1, num2 and num4 are equal, please provide different values.")
elif num1 == num3 and num1 == num4:
    print("num1, num3 and num4 are equal, please provide different values.")
elif num2 == num3 and num2 == num4:
    print("num2, num3 and num4 are equal, please provide different values.")
elif num1 == num2:
    print("num1 and num2 are equal, please provide different values.")
elif num1 == num3:
    print("num1 and num3 are equal, please provide different values.")
elif num1 == num4:
    print("num1 and num4 are equal, please provide different values.")
elif num2 == num3:
    print("num2 and num3 are equal, please provide different values.")
elif num2 == num4:
    print("num2 and num4 are equal, please provide different values.")
elif num3 == num4:
    print("num3 and num4 are equal, please provide different values.")
else:

    if num1 > num2 and num1 > num3 and num1 > num4:
        if num2 > num3 and num2 > num4 and num3 > num4:
            print(num1, num2, num3, num4)
        elif num2 > num3 and num2 > num4 and num4 > num3:
            print(num1, num2, num4, num3)
        elif num3 > num2 and num3 > num4 and num2 > num4:
            print(num1, num3, num2, num4)
        elif num3 > num2 and num3 > num4 and num4 > num2:
            print(num1, num3, num4, num2)
        elif num4 > num2 and num4 > num3 and num2 > num3:
            print(num1, num4, num2, num3)
        else:
            print(num1, num4, num3, num2)

    elif num2 > num1 and num2 > num3 and num2 > num4:
        if num1 > num3 and num1 > num4 and num3 > num4:
            print(num2, num1, num3, num4)
        elif num1 > num3 and num1 > num4 and num4 > num3:
            print(num2, num1, num4, num3)
        elif num3 > num1 and num3 > num4 and num1 > num4:
            print(num2, num3, num1, num4)
        elif num3 > num1 and num3 > num4 and num4 > num1:
            print(num2, num3, num4, num1)
        elif num4 > num1 and num4 > num3 and num1 > num3:
            print(num2, num4, num1, num3)
        else:
            print(num2, num4, num3, num1)

    elif num3 > num1 and num3 > num2 and num3 > num4:
        if num1 > num2 and num1 > num4 and num2 > num4:
            print(num3, num1, num2, num4)
        elif num1 > num2 and num1 > num4 and num4 > num2:
            print(num3, num1, num4, num2)
        elif num2 > num1 and num2 > num4 and num1 > num4:
            print(num3, num2, num1, num4)
        elif num2 > num1 and num2 > num4 and num4 > num1:
            print(num3, num2, num4, num1)
        elif num4 > num1 and num4 > num2 and num1 > num2:
            print(num3, num4, num1, num2)
        else:
            print(num3, num4, num2, num1)

    elif num4 > num1 and num4 > num2 and num4 > num3:
        if num1 > num2 and num1 > num3 and num2 > num3:
            print(num4, num1, num2, num3)
        elif num1 > num2 and num1 > num3 and num3 > num2:
            print(num4, num1, num3, num2)
        elif num2 > num1 and num2 > num3 and num1 > num3:
            print(num4, num2, num1, num3)
        elif num2 > num1 and num2 > num3 and num3 > num1:
            print(num4, num2, num3, num1)
        elif num3 > num1 and num3 > num2 and num1 > num2:
            print(num4, num3, num1, num2)
        else:
            print(num4, num3, num2, num1)

# # Restaurant Discount Decision

# A customer orders food worth ₹600.
# If bill > 500 → check membership:

# If member → give 20% discount

# Else → give 10% discount
# Calculate the final bill.

food_order = int(input("Enter total bill:"))
check_mem = input("Enter (Yes/No)")


if food_order > 500:
  if check_mem == "yes":
    print("Final bill:",food_order*0.80,"Rs")
  else:
    print("Final bill:",food_order*0.90,"Rs")
else:
  print("Final bill:", food_order,"Rs")

# Student Result Classification
# Given marks out of 100:
# If marks ≥ 40 → Pass
# If marks ≥ 75 → Distinction
# Else → Fail
# Print the correct message.

marks = int(input("Enter marks here:"))

if marks >= 0 and marks <= 100:
  if marks >= 40:
    if marks >= 75:
      print("Distinction")
    else:
      print("Pass")
  else:
    print("Fail")
else:
  print("Enter the correct marks")

# Movie Ticket Pricing
# Age-based pricing:
# If age < 12 → Child fare
# If age ≥ 12 and < 60 → Check if weekend:
# Weekend → Higher price
# Weekday → Normal price
# Write logic to print the ticket price.


age1 = int(input("Enter your age here:"))
day = input("Weekend(Yes/No):")
weekend_price = 1.20
child_fare = 100
adult_fare = 150

if age1 < 12:
  if day == "Yes":
    print(child_fare * weekend_price)
  else:
    print(child_fare)
else:
  if age1 >=12 and age1 <= 60:
    if day == "Yes":
      print(adult_fare * weekend_price)
    else:
      print(adult_fare)
  else:
    print("Senior citizen not allowed")

#  Weather Clothing Suggestion

# Given temperature:

# If temp < 15°C → Cold

# If temp < 5°C → Freezing
# Suggest clothing accordingly.

temp1 = int(input("Enter tempreature:"))

if temp1 < 15:
  if temp1 < 5:
    print("Freezing")
  else:
    print("Cold")
else:
  print("Normal tempreature")

# Electricity Consumption
# Given units consumed:
# If units ≤ 100 → low usage
# If units > 100 →
# If ≤ 300 → moderate usage
# If > 300 → high usage


unit_consumed = int(input("Enter consumed unit here:"))

if unit_consumed > 300:
  print("High usage")
else:
  if unit_consumed > 100:
    print("moderate usage")
  elif unit_consumed >=0:
    print("low usage")
  else:
      print("invalid input")

# Bank Withdrawal Check
# User enters withdrawal amount:
# If account balance ≥ amount →
# If amount <= 20,000 → allow
# Else → show “Limit exceeded”
# Else → “Insufficient balance”.

wid_amt = int(input("Enter your withdrawal amount here:"))
bal = int(input("Enter balance here:"))

if wid_amt <= bal:
  if wid_amt <= 20000:
    print("allow")
  else:
    print("limit exceeded")
else:
  print("insufficient balance")

# Online Exam Login

# User must enter:

# Correct username

# Correct password inside username check
# If both correct → login success else show specific error.

user_name = input("enter your user name here:")
user_actual_name = "akashdas"

if user_name == user_actual_name:
  pass1 = input("enter the password here:")
  pass2 = "akash1"

  if pass1 == pass2:
    print("login successful")
  else:
    print("incorrect passoword")
else:
  print("Incorrect username")

# Shopping Cart Shipping
# If cart total > 999 → free shipping
# Else →
# If location is “Metro city” → ₹50 shipping
# Else → ₹100 shipping

cart_toal = int(input("Enter cart total:"))


if cart_toal > 999:
  print("free shipping/","Your final bill is:", cart_toal)
else:
    loc1= input("Metro city (Yes/No)")
    if loc1 == "Yes":
      print("Your final bill is:",cart_toal+50)
    else:
      print("Your final bill is:",cart_toal+100)

# Bus Seat Reservation
# If seat type is “window”:
# Check if available:
# If yes → book
# Else → show “Booked”
# Else → assign normal seat.

seat_type = input("Enter seat preference:")
available1 = input("Yes/No:")

if seat_type == "window":
  if available1 == "Yes":
    print("booked")
  else:
    print("already booked window")
else:
  print("Assigned normal seat")