# -*- coding: utf-8 -*-
"""conditional statement QA solving

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vj-m5vRiGv5GsH5XhC4z2Fs5A74-m-95
"""

#Conditional Statement problem solving questions -

#🔹 Part 1: Technical Questions (10)

#- Write a program to check whether a given number is positive, negative, or zero.

num1 = 1

if(num1 > 0):
  print("Positive")
elif(num1 == 0):
    print("Zero")
else:
    print("negative")

#- Write a program that checks if a given number is even or odd.

num1=11

if(num1 % 2 == 0):
  print("Even")
else:
  print("Odd")

#- Write a program to check whether a given year is a leap year or not.

year = 1900


if year % 400 == 0:
    print("Leap Year")
elif year % 100 == 0:
    print("Not a Leap Year")
elif year % 4 == 0:
    print("Leap Year")
else:
    print("Not a Leap Year")

#- Write a program to find the greatest of two numbers entered by the user.

num1 = 1
num2 = 2

if (num1 > num2):
  print(num1)
elif (num2 > num1):
  print (num2)
else:
  print("Both are equal")

#- Write a program to find the greatest among three numbers entered by the user.

num1 = 1
num2 = 2
num3 = 3

if (num1 > num2 and num1 > num3):
  print(num1)
elif (num2 > num1 and num2 > num3):
  print (num2)
else:
  print(num3)

#- Write a program that checks whether a given number is divisible by 5 or not.

num =9

if(num % 5 == 0):
  print("divisible by 5")
else:
  print("Not divisible by 5")

#- Write a program to check whether a given character is a vowel or a consonant.

vowel= "A"

if(vowel == "A" or vowel == "a"):
  print("It is a vowel")
elif(vowel== "E" or vowel == "e"):
    print("It is a vowel")
elif(vowel== "I" or vowel == "i"):
    print("It is a vowel")
elif(vowel== "O" or vowel == "o"):
    print("It is a vowel")
elif(vowel== "U" or vowel == "u"):
    print("It is a vowel")
else:
  print("It is a consonant")

#- Write a program to check whether a student has passed or failed an exam. (Passing marks = 40).

marks = 30

if (marks >= 40):
  print("Pass")
else:
  print("Fail")

#- Write a program that checks whether a given number is within the range 10 to 50 or not.

num = 49

if num >= 10 and num <=50:
  print("It is within the range")
else:
  print('Not lies within the range')

#Write a program to check if a number is multiple of 3, multiple of 7, or neither.

num = 8

if num % 3 == 0 and num % 7 == 0:
    print("It is a multiple of both 3 and 7")
elif num % 3 == 0:
    print("It is a multiple of 3")
elif num % 7 == 0:
    print("It is a multiple of 7")
else:
    print("It is not a multiple of 3 or 7")

"""🔹 Part 2: Real-life Based Questions (10)"""

#- A shopkeeper gives a 10% discount if the purchase amount is more than 500. Otherwise, no discount. Write a program to check discount eligibility.

prod_amt = 600

if(prod_amt > 500):
  print(prod_amt*0.90)
else:
  print(prod_amt)

#- A person can vote if his/her age is 18 or above. Otherwise, not eligible. Write a program.

age= 19

if(age>=18):
  print("Eligible for voting")
else:
  print("Not eligible")

#A traffic light shows Red → Stop, Yellow → Wait, Green → Go. Write a program to print the action based on the light color.

colour = "Black"

if colour == "Red":
  print("Stop")
elif colour == "Yellow":
  print("Wait")
elif colour == "Green":
  print("Go")
else:
  print("Invalid colour")

# - A student’s grade is decided as:

#     Marks ≥ 90 → Grade A

#     Marks ≥ 75 → Grade B

#     Marks ≥ 50 → Grade C

#     Otherwise → Fail


marks = 86

if marks >= 90:
  print("Grade A")
elif marks >= 75:
  print("Grade B")
elif marks >= 50:
  print("Grade C")
else:
  print("Fail")

#- Write a program to check whether a person is child (0–12), teen (13–19), adult (20–59), or senior citizen (60+).

Age= 60

if Age >=0 and Age <=12:
  print("child")
elif Age >=13 and Age <=19:
  print("teen")
elif Age >=20 and Age <=59:
  print("Adult")
else:
  print("senior citizen")

# - A cinema ticket costs 200. If the person’s age is below 12, ticket costs 100. If age is above 60, ticket costs 150. Otherwise, normal price. Write a program.

age = 2

if age < 12:
  print("Ticket prize","=",100)
elif age > 60:
  print("Ticket prize","=",150)
else:
  print("Ticket prize","=",200)

# - A company gives a bonus to employees: If experience ≥ 5 years, bonus = 10,000 else bonus = 5,000. Write a program to calculate bonus.

exp = 2

if exp >= 5:
  print("Bonus","=",10000)
else:
  print("Bonus","=",5000)

# - A weather app shows:

#     Temp < 0 → "Freezing Weather"

#     Temp 0–20 → "Cold Weather"

#     Temp 21–35 → "Normal Weather"

#     Temp > 35 → "Hot Weather"

#     Write a program.


temp1 = 31

if temp1 < 0:
  print("Freezing Weather")
elif temp1 <=20:
  print("Cold Weather")
elif temp1 <=35:
  print("Normal Weather")
else:
  print('Hot Weather')

# - An ATM allows withdrawal only if amount ≤ balance. Otherwise, print “Insufficient Balance”. Write a program.

amt = 10000
balance = 20000

if amt <= balance:
  print("withdrawal","=",amt)
else:
  print("Insufficient balance")

# - A student gets scholarship if marks ≥ 85. Otherwise, no scholarship. Write a program.

marks = 60

if marks >= 85:
  print("Student will get scholarship")
else:
  print("No scholarship")

#____________________________________________________________________________________________

#Write a program to check if a number is multiple of 3,multiple of 5, multiple of 7, or neither.

num = 105  # Yeh wo number hai jisko hum check kar rahe hain

if num % 3 == 0 and num % 5 == 0 and num % 7 == 0:  # Agar 3,5,7 teeno se divide hota hai
    print("It is divisible by 3, 5 and 7")  # To ye print hoga aur program yahin ruk jayega

elif num % 3 == 0 and num % 5 == 0:  # Agar 3 aur 5 dono se divide hota hai
    print("It is divisible by 3 and 5")  # To ye message print hoga

elif num % 3 == 0 and num % 7 == 0:  # Agar 3 aur 7 se divide hota hai
    print("It is divisible by 3 and 7")  # To ye message print hoga

elif num % 5 == 0 and num % 7 == 0:  # Agar 5 aur 7 se divide hota hai
    print("It is divisible by 5 and 7")  # To ye message print hoga

elif num % 3 == 0:  # Agar sirf 3 se divide hota hai
    print("It is divisible by 3")  # To 3 wali line print hogi

elif num % 5 == 0:  # Agar sirf 5 se divide hota hai
    print("It is divisible by 5")  # To 5 wali line print hogi

elif num % 7 == 0:  # Agar sirf 7 se divide hota hai
    print("It is divisible by 7")  # To 7 wali line print hogi

else:  # Agar kisi bhi condition me nahi fitted
    print("It is not divisible by 3, 5 and 7")  # To ye print hoga